import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v14-appRouter";
import { locales } from "@/i18n";
import GlobalHeaderProvider from "./components/GlobalHeaderProvider";
import "./layout.css";
import Footer from "./components/Footer";
import { useTranslations } from "next-intl";
import GlobalCanvaServer from "./components/GlobalCanvaServer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export function generateStaticParams() {
  return locales.map((locale) => ({ locale }));
}

export default function RootLayout({
  children,
  params,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang={params.locale}>
      <body className={inter.className}>
        <AppRouterCacheProvider>
          <GlobalCanvaServer>{children}</GlobalCanvaServer>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
