import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v14-appRouter";
import { locales } from "@/i18n";
import GlobalHeaderProvider from "./components/GlobalHeaderProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export function generateStaticParams() {
  return locales.map((locale) => ({ locale }));
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html>
      <body className={inter.className}>
        <AppRouterCacheProvider>
          <GlobalHeaderProvider>{children}</GlobalHeaderProvider>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
