import { locales } from "@/i18n";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v14-appRouter";
import type { Metadata } from "next";
import { unstable_setRequestLocale } from "next-intl/server";
import { Inter } from "next/font/google";
import GlobalCanvaServer from "../components/GlobalCanvaServer";
import "./layout.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export function generateStaticParams() {
  return locales.map((locale) => ({ locale }));
}

export default function RootLayout({
  children,
  params: { locale },
}: {
  children: React.ReactNode;
  params: { locale: string };
}) {
  unstable_setRequestLocale(locale);
  return (
    <html>
      <body className="Core">
        <AppRouterCacheProvider>
          <GlobalCanvaServer>{children}</GlobalCanvaServer>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
